clusterName: log-migration-test
imagePrefix: registry.odigos.io
image:
  tag: v1.21.0-pre3
images:
  enterprise-instrumentor: registry.odigos.io/odigos-enterprise-instrumentor:log-migration
  enterprise-odiglet: registry.odigos.io/odigos-enterprise-odiglet:log-migration
onPremToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJsb2NhbC10ZXN0IiwiZXhwIjoxNzc1ODE4ODc2LCJpYXQiOjE3NzMyMjY4NzYsImlzcyI6Imh0dHBzOi8vb2RpZ29zLmlvIiwic3ViIjoiaHR0cHM6Ly9vZGlnb3MuaW8vb25wcmVtIn0.Leu8eJ1K5XrDDROM1csR6YnbBRwFed4bi4hTSoFUwa0qj1CX7Hwm7TsEuxzMBY36TbEIS0dyCeK6hHpLAbhevTa9XrWmzHPkaTnmJD09sz7LNqyXtuKVG16zIDG0MqdSIE5lkEbXzcAnwQJYWpuRoQUjCJLIdijwViHltYr1p7P958g0rZbPl-jSsVWuTxJRDqKkxGG6IIH_4KZlXtdTMvoeZve7hsI55bUgT-ZRLZFYjoN4WbZg3dlwQZcMduFVXmHtQjuuWCLJ_G_0SghrWtwMrjxrqmNnrkv_VegGpkPMZeTZfgaFXXI31o7qRDJFSU5R1Ag9WnR8QUqA0qcAXA
odiglet:
  ebpfProfilerEnabled: true
