package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/odigos-io/odigos/frontend/graph/model"
)

// EnableSourceProfiling is the resolver for the enableSourceProfiling field.
func (r *mutationResolver) EnableSourceProfiling(ctx context.Context, namespace string, kind string, name string) (*model.EnableProfilingResult, error) {
	panic(fmt.Errorf("not implemented: EnableSourceProfiling - enableSourceProfiling"))
}

// DisableSourceProfiling is the resolver for the disableSourceProfiling field.
func (r *mutationResolver) DisableSourceProfiling(ctx context.Context, namespace string, kind string, name string) (*model.DisableProfilingResult, error) {
	panic(fmt.Errorf("not implemented: DisableSourceProfiling - disableSourceProfiling"))
}

// ClearSourceProfilingBuffer is the resolver for the clearSourceProfilingBuffer field.
func (r *mutationResolver) ClearSourceProfilingBuffer(ctx context.Context, namespace string, kind string, name string) (*model.ClearProfilingBufferResult, error) {
	panic(fmt.Errorf("not implemented: ClearSourceProfilingBuffer - clearSourceProfilingBuffer"))
}

// ProfilingSlots is the resolver for the profilingSlots field.
func (r *queryResolver) ProfilingSlots(ctx context.Context) (*model.ProfilingSlots, error) {
	panic(fmt.Errorf("not implemented: ProfilingSlots - profilingSlots"))
}
