package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/services/profiles"
)

// EnableSourceProfiling is the resolver for the enableSourceProfiling field.
func (r *mutationResolver) EnableSourceProfiling(ctx context.Context, namespace string, kind string, name string) (*model.EnableProfilingResult, error) {
	if r.ProfileStore == nil {
		return nil, fmt.Errorf("profiling is not available")
	}
	result, err := profiles.EnableProfilingForSource(r.ProfileStore, namespace, kind, name)
	if err != nil {
		return nil, err
	}
	return &model.EnableProfilingResult{
		Status:      result.Status,
		SourceKey:   result.SourceKey,
		MaxSlots:    result.MaxSlots,
		ActiveSlots: result.ActiveSlots,
	}, nil
}

// DisableSourceProfiling is the resolver for the disableSourceProfiling field.
func (r *mutationResolver) DisableSourceProfiling(ctx context.Context, namespace string, kind string, name string) (*model.DisableProfilingResult, error) {
	if r.ProfileStore == nil {
		return nil, fmt.Errorf("profiling is not available")
	}
	result, err := profiles.DisableProfilingForSource(r.ProfileStore, namespace, kind, name)
	if err != nil {
		return nil, err
	}
	return &model.DisableProfilingResult{
		Status:      result.Status,
		SourceKey:   result.SourceKey,
		ActiveSlots: result.ActiveSlots,
	}, nil
}

// ClearSourceProfilingBuffer is the resolver for the clearSourceProfilingBuffer field.
func (r *mutationResolver) ClearSourceProfilingBuffer(ctx context.Context, namespace string, kind string, name string) (*model.ClearProfilingBufferResult, error) {
	if r.ProfileStore == nil {
		return nil, fmt.Errorf("profiling is not available")
	}
	result, err := profiles.ClearProfilingBufferForSource(r.ProfileStore, namespace, kind, name)
	if err != nil {
		return nil, err
	}
	return &model.ClearProfilingBufferResult{
		Status:      result.Status,
		SourceKey:   result.SourceKey,
		ActiveSlots: result.ActiveSlots,
	}, nil
}

// ProfilingSlots is the resolver for the profilingSlots field.
func (r *queryResolver) ProfilingSlots(ctx context.Context) (*model.ProfilingSlots, error) {
	if r.ProfileStore == nil {
		// Return nil (nullable in schema) to signal that profiling is disabled,
		// rather than a zero-value struct which would be indistinguishable from "enabled but empty".
		return nil, nil
	}
	active, withData := r.ProfileStore.ActiveSlots()
	stats := r.ProfileStore.MemoryStats()
	return &model.ProfilingSlots{
		ActiveKeys:          active,
		KeysWithData:        withData,
		TotalBytesInUse:     stats.TotalBytes,
		SlotMaxBytes:        stats.SlotMaxBytes,
		MaxSlots:            stats.MaxSlots,
		MaxTotalBytesBudget: stats.MaxTotalBytesBudget,
		SlotTTLSeconds:      stats.SlotTTLSeconds,
	}, nil
}
