apiVersion: v1
items:
- apiVersion: odigos.io/v1alpha1
  kind: Processor
  metadata:
    creationTimestamp: "2026-03-04T14:54:48Z"
    generation: 1
    name: odigos-url-templatization
    namespace: odigos-system
    resourceVersion: "1103753"
    uid: dba39e90-1556-4481-a3df-6561490067c0
  spec:
    collectorRoles:
    - CLUSTER_GATEWAY
    orderHint: 1
    processorConfig:
      workload_config_extension: odigos_config_k8s
    processorName: URL Templatization
    signals:
    - TRACES
    type: odigosurltemplate
kind: List
metadata:
  resourceVersion: ""
