# Same as action-url-templatization.yaml but target updated: caller -> callersvc
# (Tests update path: Processor stays; InstrumentationConfigs should update.)
apiVersion: odigos.io/v1alpha1
kind: Action
metadata:
  name: url-templatization-e2e
  namespace: odigos-system
spec:
  signals:
    - TRACES
  urlTemplatization:
    templatizationRulesGroups:
      - filterK8sNamespace: odigos-action-demo
        workloadFilters:
          - workloadKind: Deployment
            workloadName: go-app
            workloadNamespace: odigos-action-demo
          - workloadKind: Deployment
            workloadName: callersvc
            workloadNamespace: odigos-action-demo
        templatizationRules:
          - template: "/items/{id}"
