apiVersion: v1
kind: ServiceAccount
metadata:
  name: odiglet
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
{{- if gt (len (.Values.odiglet.serviceAccountAnnotations | default dict)) 0 }}
  annotations:
    {{- toYaml .Values.odiglet.serviceAccountAnnotations | nindent 4 }}
{{- end }}
